<?php
/**
 * Tân Hoàng Linh.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  TanHoangLinh
 * @license GPL-2.0+
 * @link    #
 */

// Initialize Genesis.
genesis();
